CREATE TABLE websites (
    WEBSITE_ID SERIAL PRIMARY KEY,
    Name VARCHAR(256),
    URL VARCHAR(1024)
);

CREATE TABLE pages (
    PAGE_ID SERIAL PRIMARY KEY,
    WEBSITE_ID INT REFERENCES websites (WEBSITE_ID),
    path VARCHAR(2048)
);

CREATE TABLE vulnerabilities (
    VULN_ID SERIAL PRIMARY KEY,
    PAGE_ID INT REFERENCES pages (PAGE_ID),
    data VARCHAR(2048)
);
